"""add last_seen_at and index machine_events integration_id

Revision ID: 78cf4a6eed5c
Revises: 566f3961b663
Create Date: 2026-09-25 11:11:43.509964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cf4a6eed5c'
down_revision: Union[str, Sequence[str], None] = '566f3961b663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_machine_events_integration_id'), 'machine_events', ['integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_events_integration_id'), table_name='machine_events')
    op.drop_column('integrations', 'last_seen_at')
    # ### end Alembic commands ###
