"""add diagnostic_details to incidents

Revision ID: a7a413cb9508
Revises: 78cf4a6eed5c
Create Date: 2026-09-25 13:12:10.222736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a413cb9508'
down_revision: Union[str, Sequence[str], None] = '78cf4a6eed5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('diagnostic_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'diagnostic_details')
    # ### end Alembic commands ###
